# Generated by Django 4.1.7 on 2023-02-20 01:54

from django.db import migrations, models
import speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to=speakers.models.link_upload_to, verbose_name='picture of the speaker'),
        ),
    ]
