# Generated by Django 4.1.7 on 2023-02-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_speakers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='image',
            field=models.ImageField(upload_to='images/speakers/', verbose_name='picture of the speaker'),
        ),
    ]
