# Generated by Django 4.1.7 on 2023-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_alter_speakers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='year the speaker took part'),
            preserve_default=False,
        ),
    ]
