# Generated by Django 4.1.7 on 2023-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='year the team member was in'),
            preserve_default=False,
        ),
    ]
