# Generated by Django 4.1.7 on 2023-02-20 01:54

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to=team.models.link_upload_to, verbose_name='picture of the team member'),
        ),
    ]
