# Generated by Django 4.1.7 on 2023-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='tile of the episode')),
                ('published_date', models.DateField(verbose_name='episode publish date')),
                ('description', models.TextField(verbose_name='description of episode')),
                ('image', models.FileField(upload_to=None, verbose_name='image used as a episode cover image')),
            ],
        ),
    ]
