# Generated by Django 4.1.7 on 2023-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='length',
            field=models.IntegerField(default=3600, verbose_name='length of podcast in seconds'),
            preserve_default=False,
        ),
    ]
