# Generated by Django 4.1.7 on 2023-02-20 01:54

from django.db import migrations, models
import episodes.models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_episodes_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.FileField(upload_to=episodes.models.link_upload_to, verbose_name='image used as a episode cover image'),
        ),
    ]
