# Generated by Django 4.1.7 on 2023-02-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_alter_episodes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='image',
            field=models.FileField(upload_to='images/episodes/', verbose_name='image used as a episode cover image'),
        ),
    ]
