# Generated by Django 3.2.18 on 2023-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0005_alter_episodes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='apple_link',
            field=models.URLField(blank=True, null=True, verbose_name='apple link to this episode'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='buzzsprout_link',
            field=models.URLField(blank=True, null=True, verbose_name='buzzsprout link to this episode'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='overcast_link',
            field=models.URLField(blank=True, null=True, verbose_name='overcast link to this episode'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='spotify_link',
            field=models.URLField(blank=True, null=True, verbose_name='spotify link to this episode'),
        ),
    ]
