# Generated by Django 4.1.7 on 2023-02-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name of the podcast media')),
                ('link', models.URLField(verbose_name='link to the podcast media page')),
            ],
        ),
        migrations.RenameModel(
            old_name='Links',
            new_name='SocialMediaLinks',
        ),
    ]
