# Generated by Django 3.2.18 on 2023-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_podcastlinks_rename_links_socialmedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastlinks',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/podcast_icons/', verbose_name='icon of the podcast page as on our www'),
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/social_icons/', verbose_name='icon of the social media platform as seen on our www'),
        ),
    ]
