# Generated by Django 3.2.18 on 2023-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20230801_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialinks',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/social_icons/', verbose_name='icon of the social media platform as seen on our www, in SVG FORMAT'),
        ),
    ]
